### ISSUE TITLE
Up arrow history

### ISSUE THREAD

**Issue by CsatiZoltan** [marcel-goldschen-ohm/EigenLab#10]
EigenLab is really fancy, it would be however nice to be able to use the up arrow for previous commands (like in Matlab). Bash e.g. supports it and uses [GNU Readline](http://cnswww.cns.cwru.edu/php/chet/readline/rltop.html) for it. Without any modification of the EigenLab source code, there is a very nice [wrapper](https://github.com/hanslub42/rlwrap) for it. I tried it and works wonderfully. It might be useful for you and the other users.

**Comment by marcel-goldschen-ohm** [comment]
Thanks for the info, looks cool. However, since EigenLab is not specifically a command line utility, I have left how user input is handled to the discretion of the individual program's UI interface. I suppose EigenLab could store a history list of evaluated expressions internally, although doing this as needed in the main program seems fine too. For command line stuff though, your suggestions look great! Thanks.
